export const CHANGE_ARTICLES_SELECT = 'CHANGE_ARTICLES_SELECT';
export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const INCREMENT = 'INCREMENT';

